# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#263238'
foreground='#EEFFFF'
cursor='#EEFFFF'

# Colors
color0='#263238'
color1='#F07178'
color2='#C3E88D'
color3='#FFCB6B'
color4='#82AAFF'
color5='#C792EA'
color6='#89DDFF'
color7='#EEFFFF'
color8='#546E7A'
color9='#F07178'
color10='#C3E88D'
color11='#FFCB6B'
color12='#82AAFF'
color13='#C792EA'
color14='#89DDFF'
color15='#FFFFFF'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
