--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#263238"
foreground="#EEFFFF"
cursor="#EEFFFF"

-- Colors
color0="#263238"
color1="#F07178"
color2="#C3E88D"
color3="#FFCB6B"
color4="#82AAFF"
color5="#C792EA"
color6="#89DDFF"
color7="#EEFFFF"
color8="#546E7A"
color9="#F07178"
color10="#C3E88D"
color11="#FFCB6B"
color12="#82AAFF"
color13="#C792EA"
color14="#89DDFF"
color15="#FFFFFF"
